#!/usr/bin/env python3
"""Pack the measured FNaF 2 cue references into an ignored ESP32 asset C file.

The source WAVs remain outside the repository. Each reference is reduced to
the same 4 kHz, 400 ms correlation core used by the external shadow matcher;
the generated C file is game-content build output and is intentionally ignored
by Git. It is consumed by the next firmware build/flash only. The firmware
carries numeric sample handles only; semantic labels remain host-side.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import pathlib
import re
import struct
import sys


HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
DEFAULT_HANDLES = (15, 16, 17, 20, 21, 23, 24, 25, 26, 27, 28, 29,
                   30, 31, 32, 33)
def load_core(path: pathlib.Path) -> bytes:
    spec = importlib.util.spec_from_file_location("cue_export_model", HERE / "export-model.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load export-model.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.resample_core(path)


def c_identifier(handle: int) -> str:
    return "fnaf2_cue_%04d" % handle


def c_int16_values(raw: bytes) -> str:
    values = struct.unpack("<%dh" % (len(raw) // 2), raw)
    rows = []
    for start in range(0, len(values), 12):
        rows.append("    " + ", ".join(str(value) for value in values[start:start + 12]))
    return ",\n".join(rows)


def generate(refs: pathlib.Path, output: pathlib.Path, handles: tuple[int, ...]) -> None:
    if output.exists():
        raise ValueError("refusing to overwrite %s" % output)
    if len(set(handles)) != len(handles):
        raise ValueError("duplicate cue handle")
    entries = []
    manifest = hashlib.sha256()
    for handle in handles:
        path = refs / ("s%04d.wav" % handle)
        if not path.is_file():
            raise ValueError("missing reference %s" % path)
        raw = load_core(path)
        if len(raw) < 256 or len(raw) % 2:
            raise ValueError("invalid core for handle %d" % handle)
        manifest.update(struct.pack("<H", handle))
        manifest.update(raw)
        entries.append((handle, raw))

    output.parent.mkdir(parents=True, exist_ok=True)
    digest = manifest.hexdigest()
    lines = [
        "/* Generated by tools/cue/pack-esp32-cues.py; do not edit. */",
        '#include "cue_assets.h"',
        "",
    ]
    for handle, raw in entries:
        lines.extend([
            "static const int16_t %s[] = {" % c_identifier(handle),
            c_int16_values(raw),
            "};",
            "",
        ])
    lines.extend([
        "const fnaf2_cue_asset_t fnaf2_cue_assets[] = {",
    ])
    for handle, raw in entries:
        lines.append(
            "    {%d, %d, %s}," % (
                handle, len(raw) // 2, c_identifier(handle)))
    lines.extend([
        "};",
        "",
        "const size_t fnaf2_cue_asset_count =",
        "    sizeof(fnaf2_cue_assets) / sizeof(fnaf2_cue_assets[0]);",
        'const char fnaf2_cue_asset_manifest_sha256[] = "%s";' % digest,
        "const uint16_t fnaf2_cue_asset_handles[] = {",
        "    " + ", ".join(str(handle) for handle in handles) + ",",
        "};",
        "",
    ])
    output.write_text("\n".join(lines), encoding="ascii")
    print("wrote %s (%d templates, %d bytes PCM, sha256=%s)" % (
        output, len(entries), sum(len(raw) for _handle, raw in entries), digest))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refs", type=pathlib.Path,
                        default=pathlib.Path("/home/pedro/fnaf-apks/cue-refs"))
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--handles", default=",".join(map(str, DEFAULT_HANDLES)))
    args = parser.parse_args()
    try:
        handles = tuple(int(value) for value in args.handles.split(","))
        if any(handle < 0 or handle > 65535 for handle in handles):
            raise ValueError("handles must fit in uint16")
        generate(args.refs.expanduser().resolve(), args.output.resolve(), handles)
    except (OSError, ValueError, struct.error) as error:
        print("pack-esp32-cues: %s" % error, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
